version: '3'

services:
  cfdns:
    image: classmatelin/cfdns:${CFDNS_VERSION}
    container_name: cfdns
    volumes:
      - ${CFDNS_CONF_DIR}:/usr/local/cfdns/conf
    environment:
      RUST_LOG: "$CFDNS_LOG_LEVEL"
    ports:
      - "9053:53/udp"
    network_mode: "bridge"
    hostname: "cfdns"